<?php

## FILE GENERATED BY MAGRATHEA.
## SHOULD NOT BE CHANGED MANUALLY

class TweetBase extends MagratheaModel implements iMagratheaModel {

	public $id, $tweet_id, $text, $stolen_from, $original_tweet;
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct(  $id=0  ){ 
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "tweets";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["tweet_id"] = "string";
		$this->dbValues["text"] = "string";
		$this->dbValues["stolen_from"] = "string";
		$this->dbValues["original_tweet"] = "string";


		$this->dbAlias["created_at"] =  "datetime";
		$this->dbAlias["updated_at"] =  "datetime";
	}

	// >>> relations:

}

class TweetControlBase extends MagratheaModelControl {
	protected static $modelName = "Tweet";
	protected static $dbTable = "tweets";
}
?>